version: '2'

services:
  backend:
    build:
      context: ${BACKEND}
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    image: ${BACKEND_HOST}:${APP_VERSION}
    container_name: ${BACKEND_HOST}
    volumes:
      - ${BACKEND}/:/app/
      - ${DATA_PATH}:/data/user
      - ${ES_DATA}/extra:/usr/share/elasticsearch/data/extra
    expose:
      - "${BACKEND_PORT}"
    entrypoint: ./start.sh ${EXEC_ENV}
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      ENV_FILE: ${ENV_FILE}
  tika:
    image: logicalspark/docker-tikaserver
    container_name: ${DC_PREFIX}-tika
    expose:
      - "9998"
    ports:
      - "1212:9998"
    environment:
      - http_proxy
      - https_proxy
      - no_proxy

networks:
  default:
    external:
      name: ${DC_NETWORK}
