version: '3.4'
services:
  nginx-dev:
    image: ${APP}-nginx-dev
    container_name: ${APP}-nginx-dev
    build:
      context: ${NGINX}
      target: development
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    environment:
      - APP
      - ES_PROXY_PATH
      - ES_HOST
      - ES_INDEX
      - ES_PORT
      - BACKEND_HOST
      - BACKEND_PORT
      - FRONTEND_DEV_HOST
      - FRONTEND_PORT
      - PORT
    ports:
      - "80:80"


networks:
  default:
    external:
      name: browser
